# Generated by Django 2.0.5 on 2018-06-05 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='code_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_Key', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now)),
                ('HTML_code', models.TextField()),
            ],
        ),
    ]
