# Generated by Django 2.0.5 on 2018-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_model',
            name='HTML_code',
            field=models.CharField(max_length=100000),
        ),
    ]
