# Generated by Django 2.0.5 on 2018-06-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180605_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='code_model',
            name='custom_Key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
